accounts:
  - id: li-us-001                # slug used everywhere
    email: "<FILL_AFTER_SIGNUP>" # will set after creating LinkedIn account
    proxy_port: 8001             # static IP at isp.oxylabs.io:8001 (45.196.56.16)
    oxy_user_env: OXY_USER_LI001 # env var names that hold creds
    oxy_pass_env: OXY_PASS_LI001
    region: us                   # two-letter country for GoLogin
    timezone: America/Los_Angeles
    locale: en-US
    geo: { lat: 34.0522, lon: -118.2437 }